# Generated by Django 4.2.1 on 2023-06-23 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machines_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_image', models.ImageField(blank=True, upload_to='images')),
                ('machine_name', models.CharField(max_length=100)),
                ('machine_location', models.CharField(max_length=100)),
                ('digital_input', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('digital_output', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('analog_input', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('analog_output', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('date_of_installation', models.CharField(max_length=100)),
                ('machine_state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users_schema"."Machines_List',
            },
        ),
    ]
