# Generated by Django 4.2.1 on 2023-06-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automac_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users_schema"."Company_List',
            },
        ),
        migrations.CreateModel(
            name='Line_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users_schema"."Line_List',
            },
        ),
        migrations.CreateModel(
            name='Machine_Kpi_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=100)),
                ('kpi_data', models.IntegerField()),
                ('kpi_unit', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'users_schema"."Machine_Kpi_List',
            },
        ),
        migrations.CreateModel(
            name='Model_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users_schema"."Model_List',
            },
        ),
        migrations.CreateModel(
            name='Plant_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('plant_location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users_schema"."Plant_List',
            },
        ),
    ]
