# Generated by Django 4.2.1 on 2023-07-25 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automac_app', '0002_company_list_line_list_machine_kpi_list_model_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_kpi_list',
            name='kpi_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='machines_list',
            name='analog_input',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='machines_list',
            name='analog_output',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='machines_list',
            name='date_of_installation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='machines_list',
            name='digital_input',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='machines_list',
            name='digital_output',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
    ]
