# Generated by Django 4.2.1 on 2023-07-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automac_app', '0003_alter_machine_kpi_list_kpi_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines_list',
            name='machine_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
