# Generated by Django 4.2.1 on 2023-07-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automac_app', '0004_machines_list_machine_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_Machine_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('machine_id', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users_schema"."all_Machine_data',
            },
        ),
    ]
